#pragma once

#define PBR_VISUALISER_VER_MAJOR 1
#define PBR_VISUALISER_VER_MINOR 2
#define PBR_VISUALISER_VER_PATCH 0

#define PBR_VISUALISER_LAST_UPDATE "02.01.2025"

#define PBR_VISUALISER_TO_STRING_VERSION(major, minor, patch) std::format("{}.{}.{}", major, minor, patch)
#define PBR_VISUALISER_TO_INT_VERSION(major, minor, patch) (major * 10000 + minor * 100 + patch)
#define PBR_VISUALISER_VERSION_INT PBR_VISUALISER_TO_INT_VERSION(PBR_VISUALISER_VER_MAJOR, PBR_VISUALISER_VER_MINOR, PBR_VISUALISER_VER_PATCH)
#define PBR_VISUALISER_VERSION_STR PBR_VISUALISER_TO_STRING_VERSION(PBR_VISUALISER_VER_MAJOR, PBR_VISUALISER_VER_MINOR, PBR_VISUALISER_VER_PATCH)